apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-database-volume
  namespace: default
  labels:
    app: postgres-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi