apiVersion: v1
kind: Service
metadata:
  name: mosquitto-proxy
spec:
  selector:
    app: mqtt-server
  type: LoadBalancer
  ports:
    - name: mosquitto-port
      port: 1883
      targetPort: 1883

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: default
spec:
  selector:
    app: mqtt-server
  ports:
  - port: 1883
  clusterIP: None
 
