apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data
  namespace: default
  labels:
    app: mqtt-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi