apiVersion: apps/v1
kind: Deployment
metadata:
  name:  aws-proxy
  namespace: default
  labels:
    app:  aws-proxy
spec:
  selector:
    matchLabels:
      app: aws-proxy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  aws-proxy
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  aws-proxy
        image:  192.168.50.10:32000/aws-proxy
        env:
        - name: ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: aws-secrets
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: aws-secrets
              key: SECRET_KEY
        ports:
        - containerPort:  8000
          name:  aws-proxy
      restartPolicy: Always