apiVersion: apps/v1
kind: Deployment
metadata:
  name:  keys-storage
  namespace: default
  labels:
    app:  keys-storage
spec:
  selector:
    matchLabels:
      app: keys-storage
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  keys-storage
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  keys-storage
        image:  192.168.50.10:32000/keys-storage
        env:
        - name: DATABASE_URI
          value: sqlite:///database.db
        ports:
        - containerPort:  8000
          name:  keys-storage
      restartPolicy: Always