---

- name: "Microk8s cluster"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: "Install EKS Snap Package"
      snap:
        name: microk8s
        channel: edge
        classic: yes
    
    - name: "Install docker"
      snap:
        name: docker
        classic: true

    - name: "Stop Microk8s"
      command: "microk8s stop"
    
    
    - name: "Create kubectl alias"
      command: "echo \"alias kubectl=\"sudo microk8s.kubectl\" \" >> /home/vagrant/.bashrc"
    
    - name: "Install python3-pip"
      apt: name="python3-pip" state=latest update_cache=yes
    
    - name: "Upload autorize registry script"
      copy:
        src: "{{ playbook_dir }}/autorize-registry.py"
        dest: /root/autorize-registry.py
        force: yes
    
    - name: "Install requisites for script"
      pip:
        name: toml

    - name: "Enable Miucrok8s Built-in Registry"
      command: "microk8s enable registry"

    - name: "Execute script"
      command: "python3 /root/autorize-registry.py"
    
    - name: "Restart docker daemon"
      command: "snap restart docker"
    
     - name: "Start Microk8s"
      command: "microk8s start"
    
    
  
