---

- name: "Kubernetes cluster"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: "Install EKS Snap Package"
      snap:
        name: microk8s
        channel: edge
        classic: true 
    
    - name: "Install python3-pip"
      apt: name="python3-pip" state=latest update_cache=yes

    - name: "Stop Microk8s"
      command: "microk8s.stop"

    - name: "Create kubectl alias"
      command: "echo \"alias kubectl=\"sudo microk8s.kubectl\" \" >> /home/vagrant/.bashrc"

    - name: "Start Microk8s"
      command: "microk8s.start"
