---

- name: "EKS cluster"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: "Install EKS Snap Package"
      snap:
        name: microk8s
        channel: edge
        classic: yes
    
    
    - name: "Install python3-pip"
      apt: name="python3-pip" state=latest update_cache=yes

    - name: "Stop Microk8s"
      command: "microk8s.stop"

    - name: "Create kubectl alias"
      command: "echo \"alias kubectl=\"sudo microk8s.kubectl\" \" >> /home/vagrant/.bashrc"

    - name: "Upload autorize registry script"
      copy:
        src: "{{ playbook_dir }}/autorize-registry.py"
        dest: /root/autorize-registry.py
        force: yes
    
    - name: "Install requisites for script"
      pip:
        name: toml

    - name: "Execute script"
      command: "python3 /root/autorize-registry.py"

    - name: "Start Microk8s"
      command: "microk8s.start"
